// <auto-generated />
namespace TradingPlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class cui_generated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cui_generated));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021029288_cui_generated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
